-- column attributes
-- INT(11) 4 bytes
-- BIGINT
-- VARCHAR(50) --> max of 50 characters, if name is 5 characters it will only store 5 characaters
-- CHAT(50) --> 50 spaces, if name is 5 character 45 will be waste
-- DATE --> YYYY-MM-DD
-- TEXT
-- BOOL
-- FLOAT
-- DOUBLE

-- Assignment to columns
-- PK --> primary key
-- NN --> Not null
-- AI --> Auto increment
-- Default/Express --> can be a data type or null
